services:
#    events.example:
#        class: eventsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    events.admin.events:
        class: eventsBundle\Admin\EventsAdmin
        arguments: [~, eventsBundle\Entity\Events, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Events }
        public: true

    events.admin.category:
        class: eventsBundle\Admin\categoryAdmin
        arguments: [~, eventsBundle\Entity\category, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: category }
        public: true
